### ISSUE TITLE
Add testing to the ODS package 

### ISSUE THREAD

**Issue by sambles** [OasisLMF/OpenDataStandards#56]
The current version of the package fails because [OpenExposureData_Spec.csv](https://github.com/OasisLMF/OpenDataStandards/blob/master/OpenExposureData/Docs/OpenExposureData_Spec.csv) can't be opened in pandas. 

- [x] Republish a fixed version
- [x] Add testing to CI 
- [x] Move this file out from `OpenExposureData/Docs/OpenExposureData_Spec.csv` to the package src directory (or convert from excel on package creation) 

**Example Trace**
```
ods_tools csv_to_parquet -c SourceReinsScopeOEDPiWind.csv -p new_file.pq

Traceback (most recent call last):
  File "/home/sam/repos/env/api/bin/ods_tools", line 8, in <module>
    sys.exit(main())
  File "/home/sam/repos/env/api/lib/python3.9/site-packages/ods_tools/oed.py", line 293, in main
    commands[kwargs.pop('command')](**kwargs)
  File "/home/sam/repos/env/api/lib/python3.9/site-packages/ods_tools/oed.py", line 216, in csv_to_parquet
    read_csv(csv_fp, file_type=file_type, **kwargs).to_parquet(parquet_fp)
  File "/home/sam/repos/env/api/lib/python3.9/site-packages/ods_tools/oed.py", line 124, in read_csv
    all_ods_fields = get_ods_fields(df_engine)
  File "/home/sam/repos/env/api/lib/python3.9/site-packages/ods_tools/oed.py", line 66, in get_ods_fields
    ods_fields_df = df_engine.read_csv(ods_field_fp,
  File "/home/sam/repos/env/api/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/sam/repos/env/api/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/sam/repos/env/api/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/sam/repos/env/api/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/sam/repos/env/api/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/sam/repos/env/api/lib/python3.9/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 69, in __init__
    self._reader = parsers.TextReader(self.handles.handle, **kwds)
  File "pandas/_libs/parsers.pyx", line 542, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 642, in pandas._libs.parsers.TextReader._get_header
  File "pandas/_libs/parsers.pyx", line 843, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1917, in pandas._libs.parsers.raise_parser_error
```

**Comment by sambles** [comment]
package fixed, but tests should be added before next release
